// src/data/productsData.js

const productsData = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    description: "Soft 100% cotton t-shirt with a relaxed fit and round neck.",
    price: 499,
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    image: "https://placehold.co/600x400?text=White+T-Shirt",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Blue Denim Jeans",
    description: "Slim fit mid-rise jeans made from stretchable denim fabric.",
    price: 1299,
    category: "Men",
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    image: "https://placehold.co/600x400?text=Denim+Jeans",
    rating: 4.6,
  },
  {
    id: 3,
    name: "Women’s Crop Top",
    description:
      "Trendy crop top with a soft cotton blend fabric and stretchable fit.",
    price: 699,
    category: "Women",
    sizes: ["XS", "S", "M", "L"],
    color: "Pink",
    image: "https://placehold.co/600x400?text=Crop+Top",
    rating: 4.4,
  },
  {
    id: 4,
    name: "Men’s Hoodie",
    description: "Warm fleece hoodie with kangaroo pocket and adjustable hood.",
    price: 1599,
    category: "Men",
    sizes: ["M", "L", "XL"],
    color: "Black",
    image: "https://placehold.co/600x400?text=Black+Hoodie",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Women’s Summer Dress",
    description:
      "Lightweight floral dress with a flowing design and short sleeves.",
    price: 1399,
    category: "Women",
    sizes: ["S", "M", "L"],
    color: "Floral",
    image: "https://placehold.co/600x400?text=Summer+Dress",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Kids Joggers",
    description: "Comfortable cotton joggers perfect for gym or casual wear.",
    price: 899,
    category: "Kids",
    sizes: ["S", "M", "L", "XL"],
    color: "Gray",
    image: "https://placehold.co/600x400?text=Joggers",
    rating: 4.5,
  },
  {
    id: 7,
    name: "Denim Jacket",
    description:
      "Classic blue denim jacket with a button front and chest pockets.",
    price: 1799,
    category: "Kids",
    sizes: ["M", "L", "XL"],
    color: "Blue",
    image: "https://placehold.co/600x400?text=Denim+Jacket",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Women’s Leggings",
    description: "High-waist stretch leggings for workout or everyday comfort.",
    price: 799,
    category: "Women",
    sizes: ["S", "M", "L"],
    color: "Black",
    image: "https://placehold.co/600x400?text=Leggings",
    rating: 4.3,
  },
];

export default productsData;
